name: actions_scriptのテスト

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: SendComment
        run: |
          gh pr commnet ${{ github.event.pull_request.number }} --body "github actions botからのコメント"
