name: actions_scriptのテスト

on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
  contents: write
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: SendComment
        run: |
          MAX_SLOT=5
          
          gh pr comment ${{ github.event.pull_request.number }} --body "$(cat <<EOF
Preview 環境の準備ができました！
🔗 URL: $MAX_SLOT
🎰 name: stg-pr-${{ github.event.pull_request.number }}
EOF
)"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
